// Shared video, capture, collection and ZIP utilities. V2 orchestration: v2.js.
'use strict';
const $=id=>document.getElementById(id), video=$('video');
let sourceURL=null, sourceName='', frames=[], saved=[], busy=false, stopped=false, ready=false, serial=0;
const stamp=t=>{t=Math.max(0,Number(t)||0);return `${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(3).padStart(6,'0')}`};
function status(s){$('status').textContent=s}
function controls(){document.querySelectorAll('[data-step],#capture,#extract').forEach(b=>b.disabled=!ready||busy);$('file').disabled=busy;$('count').disabled=busy;$('download').disabled=!saved.length||busy;$('cancel').hidden=!busy}
function eventOnce(el,name,action){return new Promise((resolve,reject)=>{let timer;const clean=()=>{clearTimeout(timer);el.removeEventListener(name,ok);el.removeEventListener('error',bad)};const ok=()=>{clean();resolve()};const bad=()=>{clean();reject(new Error('视频无法解码，请换用 H.264 MP4 或 WebM。'))};el.addEventListener(name,ok,{once:true});el.addEventListener('error',bad,{once:true});timer=setTimeout(()=>{clean();reject(new Error('读取视频超时，请尝试较短的视频或其他编码。'))},15000);try{action()}catch(e){clean();reject(e)}})}
async function seek(t){t=Math.max(0,Math.min(t,Math.max(0,video.duration-.001)));if(Math.abs(video.currentTime-t)<.0001&&video.readyState>=2)return;await eventOnce(video,'seeked',()=>{video.currentTime=t});}
function canvasAt(width=video.videoWidth){const c=document.createElement('canvas');c.width=width;c.height=Math.max(1,Math.round(width*video.videoHeight/video.videoWidth));c.getContext('2d').drawImage(video,0,0,c.width,c.height);return c}
function blobOf(c,type='image/png'){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('截图失败，请重试。')),type,.85))}
function sharpness(c){const w=160,h=Math.max(3,Math.round(c.height/c.width*w)),s=document.createElement('canvas');s.width=w;s.height=h;const x=s.getContext('2d',{willReadFrequently:true});x.drawImage(c,0,0,w,h);const p=x.getImageData(0,0,w,h).data,g=new Float32Array(w*h);for(let i=0;i<g.length;i++)g[i]=.299*p[i*4]+.587*p[i*4+1]+.114*p[i*4+2];let sum=0,sq=0,n=0;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,v=4*g[i]-g[i-1]-g[i+1]-g[i-w]-g[i+w];sum+=v;sq+=v*v;n++}return Math.round(sq/n-(sum/n)**2)}
$('choose').onclick=()=>$('file').click();
video.ontimeupdate=()=>{$('time').textContent=stamp(video.currentTime)+' / '+stamp(video.duration)};
// The V2 controller supplies candidate rendering and upload/scanning flows.
function renderFrames(){}
async function guarded(action){if(busy||!ready)return;busy=true;video.pause();controls();try{await action()}catch(e){status(e.message)}finally{busy=false;controls()}}
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>guarded(()=>seek(video.currentTime+Number(b.dataset.step))));
async function saveCurrent(){if(saved.length>=60)throw new Error('当前最多收藏 60 张，请先下载并移除部分收藏。');const t=video.currentTime;if(saved.some(s=>s.source===sourceName&&s.sourceURL===sourceURL&&Math.abs(s.time-t)<.015)){status('这个瞬间已经收藏了。');return}const c=canvasAt(),blob=await blobOf(c);saved.push({id:++serial,source:sourceName,sourceURL,time:t,blob,url:URL.createObjectURL(blob)});renderSaved();status(`已收藏 ${stamp(t)} 的原始分辨率画面。`)}
$('capture').onclick=()=>guarded(saveCurrent);
function renderSaved(){const root=$('saved');root.replaceChildren();$('savedCount').textContent=`${saved.length} 张`;if(!saved.length)root.innerHTML='<div class="placeholder"><span>♡</span><p>喜欢的瞬间，放在这里</p><small>收藏画面后，一次打包带走。</small></div>';saved.forEach(s=>{const row=document.createElement('div');row.className='saved-item';const img=document.createElement('img');img.src=s.url;img.alt=`收藏 ${stamp(s.time)}`;const text=document.createElement('small');text.textContent=stamp(s.time);text.title=s.source;const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label',`移除收藏 ${stamp(s.time)}`);del.onclick=()=>{if(busy)return;URL.revokeObjectURL(s.url);saved=saved.filter(x=>x.id!==s.id);renderSaved()};row.append(img,text,del);root.append(row)});controls()}
// Standard ZIP (STORE), CRC-32, ASCII entry names; no external dependencies.
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
async function makeZip(items){const chunks=[],central=[];let offset=0,size=0;for(let i=0;i<items.length;i++){const item=items[i],data=new Uint8Array(await item.blob.arrayBuffer()),name=new TextEncoder().encode(`StarTrace_${String(i+1).padStart(3,'0')}_${item.time.toFixed(3)}s.png`),crc=crc32(data);const head=new Uint8Array(30+name.length),v=new DataView(head.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(12,33,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);head.set(name,30);chunks.push(head,data);const dir=new Uint8Array(46+name.length),d=new DataView(dir.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(14,33,true);d.setUint32(16,crc,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,name.length,true);d.setUint32(42,offset,true);dir.set(name,46);central.push(dir);size+=dir.length;offset+=head.length+data.length}const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,items.length,true);e.setUint16(10,items.length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'})}
$('download').onclick=async()=>{if(busy||!saved.length)return;busy=true;controls();status('正在打包原图…');try{const blob=await makeZip(saved),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='StarTrace_心动收藏.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status('ZIP 已交给浏览器下载，请在下载列表中查看。')}catch(e){status(`打包失败：${e.message}`)}finally{busy=false;controls()}};
window.addEventListener('beforeunload',e=>{if(saved.length){e.preventDefault();e.returnValue=''}});
